name: Test leetcode

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install elan
        run: |
            curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
            chmod u+x elan-init.sh
            ./elan-init.sh -y --default-toolchain none
            echo "Adding location $HOME/.elan/bin to PATH..."
            echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          lake exe cache get
          lake exe leetcode
          lake exe twosum-bench